This PR adds a bug report template
buildpacks/docs pull request #406
Opened 2021-08-30 16:52 UTC by Asmit2952

Signed-off-by: Asmit2952 <asmitbm2952002@gmail.com>

2021-08-30 18:08 UTC, samj1912 approved these changes

2021-09-17 14:26 UTC, jromero requested changes

2021-09-17 14:26 UTC, jromero commented on .github/bug_report.md
> +* Please **refrain from** adding labels to your issue/pull-request on your own. It is the job of the Project Admin and the Mentors to review your issue/pull-request and add labels accordingly.
I believe `/assign` is a function of PROW which our project doesn't use. Can we change this to state that something like "if you would like to be assigned to it please comment on the issue".

2021-10-01 14:26 UTC, samj1912 commented
@Asmit2952 ping ^

2021-10-01 15:05 UTC, Asmit2952 commented
> @Asmit2952 ping ^

Sorry for replying late and making changes as I didn't get any notification regarding this.

2021-10-05 18:31 UTC, Asmit2952 commented
Any updates regarding this PR? @jromero @samj1912

2021-10-06 16:59 UTC, jromero approved these changes

2021-10-06 17:00 UTC, merged